# Generated by Django 3.1.1 on 2021-02-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210219_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coments',
            field=models.CharField(blank=True, max_length=255, verbose_name='Comments of User'),
        ),
    ]
