# Generated by Django 3.1.1 on 2023-06-25 16:51

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('owner', models.CharField(max_length=16, verbose_name='Owner')),
                ('name', models.CharField(max_length=255, verbose_name='Note Name')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True, verbose_name='Note Address')),
                ('action', models.CharField(max_length=32, verbose_name='Note Action')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('unspecified', 'Unspecified'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='unspecified', max_length=20, verbose_name='Status')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('priority', models.IntegerField(verbose_name='Priority')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('date_completed', models.DateField(default='2023-12-31', verbose_name='Date Completed')),
                ('flag_alive', models.CharField(max_length=1, verbose_name='ActiveAlive ?')),
                ('project_id', models.CharField(max_length=12, verbose_name='Project')),
                ('persistent', models.CharField(max_length=1, verbose_name='Persistent')),
                ('category', models.CharField(max_length=1, verbose_name='Catg')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
