# Generated by Django 3.1.1 on 2021-02-21 16:41

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_firmness'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='country_of_origin',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country of Origin'),
        ),
    ]
